# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2022-08-03 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.SmallIntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0)),
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=50, unique=True)),
                ('picture', models.ImageField(blank=True, upload_to='my_picture')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.SmallIntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0)),
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('book_type', models.CharField(choices=[('ebook', 'ebook'), ('nbook', 'nbook')], max_length=50)),
                ('extra_det', models.CharField(max_length=100)),
                ('book_file', models.FileField(blank=True, upload_to='my_file')),
                ('author', models.ManyToManyField(blank=True, related_name='book_author', to='Libsys.Author')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('hardCopy_id', models.AutoField(primary_key=True, serialize=False)),
                ('isLent', models.BooleanField(default=False)),
                ('book_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_info', to='Libsys.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('approval_status', models.SmallIntegerField(choices=[(1, 'Approved'), (0, 'Rejected'), (2, 'Pending for approval')], default=2, max_length=30)),
                ('book_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_location', to='Libsys.Book')),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='Libsys.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('lang_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('script', models.CharField(max_length=20)),
                ('about', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('pub_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact_details', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.SmallIntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0)),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20)),
                ('mobile_no', models.CharField(max_length=12)),
                ('email_id', models.EmailField(max_length=50)),
                ('subscription', models.BooleanField(default=False)),
                ('favorite', models.ManyToManyField(blank=True, related_name='favorite', to='Libsys.Book')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role', to='Libsys.UserRoles'),
        ),
        migrations.AddField(
            model_name='ebook',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebook_user', to='Libsys.User'),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='lentTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lent_book', to='Libsys.User'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ManyToManyField(blank=True, related_name='book_language', to='Libsys.Language'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_publisher', to='Libsys.Publisher'),
        ),
    ]
