# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2022-08-17 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libsys', '0004_auto_20220804_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite',
        ),
        migrations.AddField(
            model_name='user',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favourite', to='Libsys.Book'),
        ),
    ]
