# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2022-08-17 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Libsys', '0005_auto_20220817_0553'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='lang_id',
            new_name='language_id',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='pub_id',
            new_name='publisher_id',
        ),
    ]
